apiVersion: apps/v1
kind: Deployment
metadata:
  name: virt-disk-operator
  namespace: virt-disk-operator
  labels:
    app.kubernetes.io/name: virt-disk-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: virt-disk-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: virt-disk-operator
    spec:
      securityContext:
        runAsUser: 65532
        runAsGroup: 65532
        runAsNonRoot: true
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        image: ghcr.io/gpu-ninja/virt-disk-operator:latest
        name: manager
        ports:
        - name: metrics
          containerPort: 8080
        - name: healthz
          containerPort: 8081
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 64Mi
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: run-user
          mountPath: /run/user/65532
      volumes:
      - name: run-user
        emptyDir:
          medium: Memory
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
