apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: virt-disk-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: virt-disk-operator
    app.kubernetes.io/part-of: virt-disk-operator
  name: virt-disk-operator