apiVersion: v1
kind: Service
metadata:
  name: virt-disk-operator-metrics
  namespace: virt-disk-operator
spec:
  selector:
    app.kubernetes.io/name: virt-disk-operator
    app.kubernetes.io/component: metrics
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080