apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: virt-disk-operator
    app.kubernetes.io/part-of: virt-disk-operator
  name: controller-manager
  namespace: virt-disk-operator
